version: 2
jobs:
  build:
    working_directory: ~/node-module-glpi
    docker:
      - image: circleci/node:8.5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: generate a configuration file
          command: ci/create-config-file.sh
      - run:
          name: test
          command: npm test